{"name": "test_01[data2]", "status": "broken", "statusDetails": {"message": "KeyError: 'user_id'", "trace": "self = <class 'autotest.testcases.exception_testing.test_api_exception_case.Test'>\n\n    def setup_class(self):\n        self.compare_results = CompareResults()\n        self.test_files = getTestFile()\n>       self.sd = SendRequest()\n\ntestcases\\exception_testing\\test_api_exception_case.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\base_utils\\Request.py:14: in __init__\n    self.applet_res = Applet_Login().applogin(create_phone())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <common.login.applet_login.Applet_Login object at 0x000001BB793D9A90>\ntenantype = '17732752316', phone = None\n\n    def applogin(self,tenantype,phone=None,):\n        #获取验证码\n        result = djy_get_vcode(phone, '1000001', cf.applet_appkey)\n        vcode = result\n        result = applet_login(phone, vcode, '1000001', cf.applet_appkey, tenantype)\n>       self.Guid = result['Data']['user_id']\nE       KeyError: 'user_id'\n\ncommon\\login\\applet_login.py:23: KeyError"}, "parameters": [{"name": "data", "value": "['case003', '手机号码为空，获取验证码', 'http://djy-web-fat3.woda.ink/api/v1/VCodeManager/GetVCode', None, True, {'SPhone': '112@多少'}, {'Code': 300, 'Data': '', 'Desc': '手机号码无效'}, '是']"}], "start": 1594631307031, "stop": 1594631307031, "uuid": "1c0c19fa-e8e5-4a17-aa5c-5ef6ea175f8d", "historyId": "5a6537b651c4a1902ffb80babd2d700b", "testCaseId": "103acbfa39814fc758dbae7e86c33b94", "fullName": "testcases.exception_testing.test_api_exception_case.Test#test_01", "labels": [{"name": "parentSuite", "value": "testcases.exception_testing"}, {"name": "suite", "value": "test_api_exception_case"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "DESKTOP-9JNMRHP"}, {"name": "thread", "value": "26496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.exception_testing.test_api_exception_case"}]}